### ISSUE TITLE
[APP] Uninstalling the fleet will uninstall all JetBrains app.

### ISSUE THREAD

**Issue by BennettChina** [alienator88/Pearcleaner#101]
>NOTE: If a specific app is finding unrelated files or not finding expected files, use the new condition builder to either include or exclude files from the search. Push CMD+B when you're on an app's page to show the condition builder.

**Describe the app**

Uninstalling the fleet will uninstall all JetBrains app. Maybe the path containing the app name should be searched first?

**App Details**
1. Name: Fleet
2. Version: 1.17.63
3. Source (Toolbox Download)
4. Type (Regular)

**Desktop (please complete the following information):**
 - OS: [14.5]
 - Pearcleaner App Mode: [Regular]
 - Pearcleaner Version: [3.8.5]

**Screenshots**

<img width="846" alt="image" src="https://github.com/user-attachments/assets/0a43d7c5-86db-4c71-a29c-ed71d795e387">

**Comment by alienator88** [comment]
This is by design, there's a condition set in the app where if the bundle identifier contains "jetbrains", it should search for folders named "jetbrains": https://github.com/alienator88/Pearcleaner/blob/b142c62de02afcee606f5ac6544982eb6c64d771/Pearcleaner/Logic/Conditions.swift#L130-L136

The reason for this is that when uninstalling jetbrains apps, the jetbrains cache folders were never found.
If you want, you can try adding an exception for the keyword "jetbrains" in the Fleet app by doing the following:
1. Open Fleet app in Pearcleaner
2. Push CMD+B to launch the condition builder
3. Add `jetbrains` in the Exclude Keywords field

![image](https://github.com/user-attachments/assets/3b5d9cae-fbc5-44db-a6ed-194270194167)

Note, this might hide fleet related files that contain the word "jetbrains" as well. 
Usually when developers have multiple apps under a similar enough bundle identifier, shared files will show up. Which is why Pearcleaner has a warning instructing the user to make sure they verify the items marked for deletion.
