### ISSUE TITLE
[BUG] Homebrew cleanup not running when starting pearcleaner from trash sentinel monitor 

### ISSUE THREAD

**Issue by apotenza92** [alienator88/Pearcleaner#110]
**Describe the bug:** <br>
If using sentinel monitor to detect when apps are dragged into trash anything uninstalled using that method will not run the homebrew cleanup

**Expected behavior** <br>
Normal pearcleaner uninstall where brew cleanup works.

**Info:**
 - 15.0
 - Pearcleaner Version: 3.8.7

**Comment by apotenza92** [comment]
Hi, slightly related by could be a new issue:
I just tried to uninstall logi options + using pearcleaner and when it went to run the homebrew cleanup it couldn't find the correct cask name. It looked up 'logioptionsplus' but the cask name is logi-options+. Not sure why this would've happened maybe the cask name has changed recently?

**Comment by alienator88** [comment]
The sentinel monitor issue is likely just a small bug. When I added the brew cleanup function, I probably forgot to add it to the monitor as well. I'll take a look at it and see.

The logioptions thing is likely just the different naming convention Logi set for their mac app and the homebrew cask identifier. Most app devs set the cask identifier to the same name as their app but with dashes instead of spaces if it has any.
Logi went with a completely different cask identifier than what the app name shows in Pearcleaner. I'm not sure how to fix this really besides hardcoding a check for the Logi app specifically in the code.
If I could list installed brew casks via bundle identifier it would solve all these issues, but I don't think brew has that option. I'll see if I can find a workaround.

**Comment by alienator88** [comment]
Both of these issues should be fixed now. It will be released in the next version.
