### ISSUE TITLE
[BUG] TouchID auth not working

### ISSUE THREAD

**Issue by mightysashiman** [alienator88/Pearcleaner#123]
**Describe the bug:** <br>
Trying to uninstall an app requiring privilege escalation to proceed, app asks for auth. If using TouchID (that is default when TouchID is set up) fails, forcing user to use password input workaround.

**Steps to reproduce:**
1. have an app that requires privilege escalation to install
2. figure you need to uninstall it
3. select it for uninstall within pearcleaner and proceed
4. this window will appear:
<img width="908" alt="Screenshot 2024-10-13 at 10 42 22" src="https://github.com/user-attachments/assets/7815f023-695c-48d2-a7e4-ec8b196377dd">

5. Try using touchID, it beachballs for a while but nothing happens
6. switch to "Use password", it works

**Expected behavior** <br>
TouchID auth should work

**Info:**
 - OS: [15.0.1]
 - Pearcleaner Version: [e.g. 3.9.1]

**Comment by alienator88** [comment]
Hey what's up man!
So this was discussed here before: https://github.com/alienator88/Pearcleaner/issues/107

It's a limitation of AppleScript not being allowed to use touchID for auth. Nothing I can do about it unfortunately, Apple would need to allow it. I'm not sure if it a new bug with Sequoia or what.

**Comment by mightysashiman** [comment]
> It's a limitation of AppleScript not being allowed to use touchID for auth. Nothing I can do about it unfortunately, Apple would need to allow it. I'm not sure if it a new bug with Sequoia or what.

Would _not_ using AppleScript in your app be a way round this limitation? That would of course imply reimplementing (in swift?) what is currently done through AppleScript.

**Comment by alienator88** [comment]
Well yeah, of course 😂 
But the reason for using AppleScript is that I'm using Finder to delete files which allows for undo functions.
I looked at implementing undo manually and it was a headache for when there are files of the same name in different folder paths. Finder automatically renames them using a timestamp and keeps track of them somewhere when putting the files in the Trash. Then when you undo, it renames them back and remembers all those paths.
I would also need to add another helper binary in order to be able to execute admin functions without Finder running with Administrator Privileges permission.
Just too much of a lift currently for what it would accomplish.
