### ISSUE TITLE
[BUG] Orphaned Files

### ISSUE THREAD

**Issue by rsyncOSX** [alienator88/Pearcleaner#130]
### Describe the bug:
I don't know exactly how the  Orphaned Files is supposed to work, but I would think it list files which might be deleted due to the application itself is deleted. 

### Expected behavior:
I would expect it not to delete files if the application itself is not deleted. But it picks files from application which are not deleted as well. I had to reactivate my DxO PL 8 application after cleaning all Orphaned Files. I did another list of Orphaned Files and it picks up DxO PL 8 files again. 

### Info:
 - OS: [e.g. 15.0.1]
 - Pearcleaner Version: [e.g. 3.9.2]

### Screenshots:

<img width="1287" alt="Screenshot 2024-10-20 at 16 54 22" src="https://github.com/user-attachments/assets/8e40bfcb-8477-407b-b39f-b1e7a6cc64db">
<img width="1287" alt="Screenshot 2024-10-20 at 16 54 57" src="https://github.com/user-attachments/assets/bfb1ef0f-9aac-4107-8216-77b0f42398fc">

**Comment by alienator88** [comment]
There should be a warning that pops up the first time you open the Orphaned Files view saying something like the search is not 100% accurate and the user should verify the files they are deleting. The reason those get picked up is because the app's name and bundle identifier don't match any of those files. You can right click and exclude folders or files from the orphaned file search.

**Comment by rsyncOSX** [comment]
OK, understand.. Thanks for clearing up, closing the the issue...
