### ISSUE TITLE
[BUG] Finder Extension Energy Impact

### ISSUE THREAD

**Issue by SuperLeiyan** [alienator88/Pearcleaner#132]
Energy use seemed to have gone up significantly since the latest update
![image](https://github.com/user-attachments/assets/be8f7e91-b909-4e5d-ae4c-c963a94f1e9c)

### Info:
 - OS: 14.6.1
 - Pearcleaner Version: 3.9.2

**Comment by alienator88** [comment]
That looks to be the finder extension for Pearcleaner. It should only be activated while Finder is in use. And even that should be extremely small energy usage.
I'm not seeing the same on my end, it's just sitting at `0.0` for me. 
It could be a macOS extension bug or glitch.
Have you already tried turning the Pearcleaner finder extension off and on and maybe reboot computer?

**Comment by alienator88** [comment]
I've left it running for a while now and I'm seeing the increase that you're seeing.
The thing is I've never looked at the energy impact before so not sure if this has been happening before or not.
And super confusing too why it would use that much because the extension doesn't do anything at all when not in use. 
All it does is adds a context menu item to the apps in Finder.
I'm looking into it to see if it's a FinderSync bug, that's what Finder uses to allow extensions inside it.

**Comment by SuperLeiyan** [comment]
I don't think it was happening before 3.9.2. Would disabling Finder Extension be a temporary fix?

**Comment by alienator88** [comment]
Yeah, if the issue is only on the FinderOpen process. In your screenshot you highlighted the FinderOpen process only.
Does the Pearcleaner process itself have the same issue? Or only the extension.
I'd be curious if you can see the same problem on version 3.9.1 now or if it goes away.
The strange thing is I haven't touched the finder extension code in a long time, so I have no idea what might've changed.

**Comment by SuperLeiyan** [comment]
Turned off Finder Extension for now, I'll leave it running for a while and report back. Perhaps in the meantime run 3.9.1 on your machine.

**Comment by alienator88** [comment]
I tested 3.9.1 and it seems to do the same thing.
The only thing that might've affected the extension is moving from Sonoma to Sequoia. I started building the app using Xcode 16 instead of 15. 
So if macOS introduced any new bugs/changes in the FinderSync library, it's possible it caused these issues. Which I'm pretty sure they have because Finder extensions don't even show up in the Settings page anymore for Finder extensions. Something is definitely broken there now in Sequoia.

Plus like I said, I haven't touched the code of that extension in a very long time.
I'm thinking this will eventually sort itself out once Apple adds more fixes to Sequoia.
