### ISSUE TITLE
Slovak localization

### ISSUE THREAD

**Issue by Svec-Tomas** [alienator88/Pearcleaner#140]
Please find attached the Slovak translation of Pearcleaner.

[Localizable.xcstrings.zip](https://github.com/user-attachments/files/17532050/Localizable.xcstrings.zip)

**Comment by alienator88** [comment]
Hey @Svec-Tomas, so the strings catalog you have attached doesn't seem to have all of the words, maybe because it was copied a while back and new strings have been added since to fix some issues.
Would you be able to convert the translation via one of these 2 ways?
1. Translate using the attached .xcloc file using Xcode or Loca Studio and send it back to me so I can import directly
2. Clone the Pearcleaner repo locally, make changes to the Localizable file and then open a pull request so I can review and merge

Making the changes to the strings catalog directly and sending it to me doesn't give me a clean way to merge it into the repo.

[sk.xcloc.zip](https://github.com/user-attachments/files/17563761/sk.xcloc.zip)

**Comment by Svec-Tomas** [comment]
1. I have downloaded the attached file and opened it in Loca Studio, but it seems to have no strings translated to Slovak.
2. I am not familiar with cloning repo, so I don't know what to do.

Can you tell me please what exactly I should do, please?

**Comment by alienator88** [comment]
So the attached file is empty, but up to date with all the required strings. If you could copy over the strings already translated from the localizable file to the xcloc file, that would be great. There should be a few new strings leftover that don't have translations yet.

I tried to export the strings from your localizable file but wasn't able to.

**Comment by Svec-Tomas** [comment]
Please check the attached translation.

I hope this time it will be OK.

[sk.xcloc.zip](https://github.com/user-attachments/files/17606788/sk.xcloc.zip)

**Comment by alienator88** [comment]
Sorry, just got to this.
I was able to import it and it looks to be 100% complete. I'll have this out with all the other completed languages in the next release.
Thank you! :)
