### ISSUE TITLE
[APP] Random files get deleted only slightly related by containing part of the app name

### ISSUE THREAD

**Issue by fluxor99232** [alienator88/Pearcleaner#144]
Random files get deleted. Only similarity with the correct ones I can recognize is that the filename contains part of the app name. Is that really how files to get deleted are identified?? I find that rather disturbing.

**Describe the app**

A clear and concise description of what the affected app issue is.

**App Details**
1. Name: Google Chrome
2. Version: 109.0.5414.119
3. Source: Website Download
4. Type: Regular

**Desktop (please complete the following information):**
 - OS: 15.1
 - Pearcleaner App Mode: Regular
 - Pearcleaner Version: 3.9.3

**Screenshots**

![CleanShot 2024-11-05 at 14 44 08@2x](https://github.com/user-attachments/assets/bf8c9787-6838-4fa1-851e-f677dd0d4581)

**Comment by alienator88** [comment]
That's how these app cleaner type apps work, they use some custom search algorithms based on the app names and bundle identifiers. Thank Apple for that as the OS doesn't track where apps dump all their files so the only way to find them is by file/folder names.
That's why there's a warning the first time you use the app mentioning that users need to confirm the found/selected files are part of the application before deleting.

You can add a condition to any app within Pearcleaner though.
When you're on the Google Chrome screen in your screenshot, hit CMD+B and type `affinity` in the Exclude Keywords field and click Add.
Then search again for the files and it will exclude those affinity files.
![image](https://github.com/user-attachments/assets/6b46429b-5da9-411d-912c-1905db3cc129)

**Comment by alienator88** [comment]
I added an exception to exclude monochrome related files when searching for google chrome files.
Will have that out in next release.
