### ISSUE TITLE
[FR] Add multiple app support for sentinel monitor and drag/drop

### ISSUE THREAD

**Issue by bio1020** [alienator88/Pearcleaner#145]
### Describe the bug:
The Trash Sentinel function does not recognize deletion of multiple APPs at one time.

### Steps to reproduce:
1. Go to '/Applications'
2. Choose two applications
3. Move them to Trash
4. Pearcleaner will automatically open, prompting you to delete one of the applications. After clicking the uninstall button, you will no longer be prompted to clean the second application.
   

### Info:
 - OS: 15.1
 - Pearcleaner Version: 3.9.3

**Comment by alienator88** [comment]
I added some logic where if you Trash or drag/drop multiple apps, it will queue them up in a list at the bottom.
When you delete the first one in the list, it will then load the next one. I also added the ability to remove them from the list using the minus buttons.
![Screenshot 2024-11-08 at 1 18 56 PM](https://github.com/user-attachments/assets/4fcc7b14-919b-4fa8-8b8d-641845d6a34d)

I'll have this out in the next release.

**Comment by lucky13820** [comment]
Can you make it automaticly delete all the queued apps, instead of me click uninstall one at a time?

**Comment by alienator88** [comment]
I don't think I would want to add that in for a few reasons:
1. If a user has homebrew cleanup enabled, that still requires manual intervention since homebrew requires typing in the sudo password to remove an app from its Cask directory.
2. If the setting to permanently delete files instead of send to trash is enabled, this could wipe away unintended files with no way to get them back
3. Some apps might find unrelated files when they have names that are very close to other apps. Users should be looking at the list of found files to make sure they are part of the app before deleting all the files. I've had users complain because the app found some files unrelated to the app they were searching in and they just hit the Trash button without even looking at the list. if I automated that or even added the option to auto-delete as a setting, people would still be yelling. A lot of people don't seem to read the big warning popup when first opening Pearcleaner for the first time in the file list view.

Because a lot of non-technical users don't really read warnings much or ignore them, I don't want to provide ways to automate destructive actions. I hope you understand, sorry if it wasn't the answer you were looking for 😢
