### ISSUE TITLE
[FR] Track clipboard for paths to add to include/exclude folders + support copy&paste

### ISSUE THREAD

**Issue by eugenesvk** [alienator88/Pearcleaner#152]
**Is your feature request related to a problem? Please describe.**

Drag&drop, while common, isn't the most ergonomic gesture

**Describe the solution you'd like**

It's much easier to navigate in your file manager to a folder, press ⌘C to copy it, then switch back to Pearcleaner, and either paste or have it auto-suggest based on clipboard tracking.

**Describe alternatives you've considered**

Copy, click on the "+" to invoke system's file picker, and paste there, but then you have to remeber the default shortcut which you don't use anywhere else (eg, even in Finder you've changed it in the menu, but it doesn't work in the file picker), it's also slower

**Additional context**

n/a

**Comment by alienator88** [comment]
Got this done, it works two ways:
1. You can copy the file path of a folder by right clicking the folder in Finder's status bar and selecting "Copy folder as Pathname".
![image](https://github.com/user-attachments/assets/4eaa8cc1-0343-4a39-a39e-927cdeb665c7)
2. You can copy the folder directly with ⌘+C and Pearcleaner will extract the fileURL from the copied folder.

Since there's two folder lists in the Folder settings page, I don't want it to auto-suggest or do it automatically since I don't know which folder list the end user will want to add to. 
To work around this, I just added a clipboard button next to the Add Folder button. Clicking it just adds the folder of the last item added to the clipboard:
![image](https://github.com/user-attachments/assets/643a57d0-3e8b-4488-a7f6-d750588a614e)

Will have this out in the next release.
Thanks!

**Comment by eugenesvk** [comment]
The clipboard button doesn't appear in v4, although the functionality seems there - clicking to the right of the plus sign adds the path

**Comment by alienator88** [comment]
Dammit..the SF Symbol for that clipboard icon is only available in macOS 15.0.
Let me patch it and re-release 4.0.0

**Comment by alienator88** [comment]
Go ahead and re-download 4.0.0, should work now.

**Comment by alienator88** [comment]
No problem at all, thanks for finding everything
