### ISSUE TITLE
[BUG] PASSWORD REQUEST UNFOCUSED AND ASSUMES DELETION

### ISSUE THREAD

**Issue by philocalyst** [alienator88/Pearcleaner#179]
### Describe the bug:
When deleting an application that asks for admin privileges, the window is unfocused. If you click off the window, pear cleaner marks the application as deleted (although it really is not) and will not show it again until the app is restarted.

### Steps to reproduce:
1. Start pearcleaner
2. Delete an application 
3. If admin privileges are requested, you will see it is unfocused.
4. Click away from the popup
5. Observe the deletion sound and missing app in pearcleaner, and how they are just slight of hand.
   

### Expected behavior:
The window to be focused and for pearcleaner not to gaslight me.

### Info:
 - OS: 15.1.1 (24B91)
 - Pearcleaner Version: 4.02

**Comment by alienator88** [comment]
I actually have code that is there to catch when a user cancels out of the password prompt, but now in Sequoia, it doesn't return null anymore when you Cancel. This is because I'm not asking for the password myself, it's actually Finder who is asking for it. If you notice when the prompt comes up, it says Finder is asking for the password, not Pearcleaner.
So I don't really have any control over how the popup is presented. The popup itself seems to be active, it's just the textfield for the password that is not selected.

I just tested this in Script Editor outside of Pearcleaner and it has the same exact issue with the focus and the Cancel not showing a null error.

I'll try to see how I can work around this, but it seems some changes in Sequoia/Finder is making AppleScript behave this way now.

**Comment by alienator88** [comment]
I found a workaround for the focus issue so that's fixed.

For the other issue, since I can't get an error returned to me from Finder's authentication prompt, I added a check when the delete action finishes to see if all files were deleted. If they aren't(like when cancelling the prompt), it undoes the action. I'll have this out in the next release.

This should be an okay workaround for now, but I will look into adding a helper tool in the near future to execute the sudo delete actions for me instead of running it through Finder via AppleScript.

**Comment by philocalyst** [comment]
How awesome! Then the only thing is the focus... I can do a screen recording if you'd like, but I am very confident it is not focused (No border, tab not changing field). Here is a screenshot of right after trying to delete:
<img width="649" alt="image" src="https://github.com/user-attachments/assets/520f1b51-c769-4a0d-b59e-c71c306eda19" />

Would more system info matter here? Running lots of tools.

Thank you for having such minute-by-minute agency in your project -- the details matter!

**Comment by alienator88** [comment]
Can you try this debug build for me? I added an extra activate command in the Finder script to try and bring it to the very front. On my end, the password/touch id popup shows activated now.
[Pearcleaner.zip](https://github.com/user-attachments/files/18132076/Pearcleaner.zip)

**Comment by philocalyst** [comment]
Yep! Everything is golden! Thanks again for the beautiful work, heavenly.

**Comment by alienator88** [comment]
Good to hear, I'm glad it's working now!
I will have the release build out soon hopefully, just waiting on someone else to add some new language translations before I release 4.0.3.
The debug build I gave you isn't signed/notarized by the way if you care about that. It shouldn't cause any issues though.
