### ISSUE TITLE
[FR] Remove Remaining Files from Already Removed Apps

### ISSUE THREAD

**Issue by Anvil5465** [alienator88/Pearcleaner#23]
**Is your feature request related to a problem? Please describe.**

There are some apps that I've already removed before installing Pearcleaner which left some leftover files. As it is, I have to reinstall apps I've removed and uninstall them using Pearcleaner or just find leftover files myself, which is a bit tedious.

**Describe the solution you'd like**

It would be nice if Pearcleaner had a feature to scan for and remove leftover files from previously removed apps. Nektony's App Cleaner & Uninstaller can do this (https://nektony.com/mac-app-cleaner)

**Comment by alienator88** [comment]
That's funny you mention that, I'm currently working on this feature 😂 
Trying to do a reverse search where it checks files against all currently installed apps, and what doesn't match gets spit out as leftover zombie files.
It will probably take me a little bit to get this one fully fleshed out, but it's on the roadmap for sure!

**Comment by alienator88** [comment]
Added in v3.0.0

**Comment by yyzguy** [comment]
I'm really curious about the Orphaned File cleaner.   Could you explain a bit further how it works?    I'm currently on my 5th Mac since 2008 and the Orphaned file cleaner has located 433 files, 3.04GB.    Some of these files I definitely recognize as things I no longer use.   Others, I'm not as sure about, so I'm hesitant to blindly clean them up.   I'm particularly interested in knowing if files/folers from older built-in apps might still be used by the OS.   For example, iWork '08 files or iTunes or iPhotos.   Is it possible the modern replacements are still expecting some of those?    I used to use Adobe Reader  (who didn't?), but is it possible other apps still need library files from Adobe?   These are just examples, so maybe if you could explain how the Orphan file finder works, I'd have a better understanding of what's safe to remove.    Also, is this the best place to ask, or do you have another support channel.   Thanks

**Comment by alienator88** [comment]
Hey, sorry for the delay in my response, was busy with the holidays and all that.
So the main logic behind the orphaned file search is it will search for leftover files in these locations:
https://github.com/alienator88/Pearcleaner/blob/9b09a052ef4aa14d6dd934dbca81dcb05bc79d25/Pearcleaner/Logic/Locations.swift#L83

But it will attempt to exclude files related to currently installed applications. This works for most apps, but some developers name the files in ways that don't match the app name or bundle identifier. So there might be some stragglers in that list that could possibly be part of a currently installed application. When in doubt, I would say just leave the file and don't delete it.

**Comment by yyzguy** [comment]
Gotcha.  So as long as a developer used consistent naming conventions the files should be fine to delete.   Pretty neat.

When deleting an existing installed app do you have a different way of finding the other files? Do installed apps have some way of indicating where the associated files are stored (or supposed to).

**Comment by alienator88** [comment]
I basically use the same function to find the application files, just searches more folders:
https://github.com/alienator88/Pearcleaner/blob/9b09a052ef4aa14d6dd934dbca81dcb05bc79d25/Pearcleaner/Logic/Locations.swift#L28-L72

And no, unfortunately macOS doesn't have an easy way to see what locations files are generated in by applications, hence the "hacky" searching by app name and bundle id. Closest thing it has to that is the BOM file list, but that usually only tells you the files that are contained in the app bundle itself.

**Comment by yyzguy** [comment]
That’s unfortunate.  That’s probably why Apple doesn’t provide a native uninstaller.   I guess it’s still better than Windows with the whole registry mess.   I’m so happy to no longer have to figure out those things which could break the entire operating system if the wrong entries are inadvertently removed.
