### ISSUE TITLE
[BUG] Button icons not showing in app deletion view

### ISSUE THREAD

**Issue by greg1075** [alienator88/Pearcleaner#29]
**Toggle button icons in app deletion view are showing a question mark inside a square placeholder instead of the correct button icons or labels**

**To Reproduce**

1. Click app to delete in mini mode
2. See bottom of deletion window.

**Expected behavior**

I'm thinking the window is supposed to display button icons or labels?

 - macOS: 14.3.1
 - Pearcleaner App Mode: Mini Mode
 - Pearcleaner Version: 3.0.1

**Screenshots**

![Screenshot 2024-03-03 at 3 43 08 PM](https://github.com/alienator88/Pearcleaner/assets/28992145/1e0c4a5b-cc08-4e33-8268-fec3689d41a8)

**Additional context**

**Comment by alienator88** [comment]
Out of curiosity, do you still see the issue if you install the SF Symbols app from Apple? If no, that might be why I’m not seeing the issue.

**Comment by alienator88** [comment]
I do like the `textformat.abc` option so I'll switch to that. I'll probably stick with the `number` pound sign for the sizes as it literally means number and couldn't find something else that relates better. I want to stay away from using word labels to keep it more minimalistic. Users can hover over any button in the app to get a tooltip that says what it does anyways.

Fixed in next version.
