### ISSUE TITLE
Show how much space will be freed

### ISSUE THREAD

**Issue by strash** [alienator88/Pearcleaner#40]
![Frame 2241](https://github.com/alienator88/Pearcleaner/assets/14233263/0c5120d5-c30c-4488-a2cc-549712ec9a87)

Current implementation shows only how much garbage has been found but it is unclear how much will be deleted.

How can we improve this:

1. show somewhere a number of selected items and how much space they take up 
2. recalculate every time a checkbox was toggled
3. show a proper button for main action
4. also why is the number of items underlined? :)

**Comment by alienator88** [comment]
You'll laugh at this, but when I was working on some things for this app recently, I was confused why the size was not updating as I was selecting items from the list. I completely spaced that I only coded the ability to get the total only 😂 so I definitely have this in my to-do list. 
Also, I'm really digging the trash button with size next to it. I might do something similar if that's okay with you.

**Comment by strash** [comment]
Sure, it would be great!

**Comment by strash** [comment]
I might come up with more suggestions if you don’t mind.

**Comment by alienator88** [comment]
Yeah go for it!

**Comment by alienator88** [comment]
Just a quick update, haven't released this version yet in case you had something else to add. I'll hold off for now.
Added the item count in the existing location at the top to make use of that same space since it's already there. 
Then added the red button which I have to agree looks much better than before :)

![Screenshot 2024-04-06 at 6 01 58 PM](https://github.com/alienator88/Pearcleaner/assets/6263626/2d05e4c7-bd0b-45f0-9e9f-49cceea471a5)

Also added a sort setting to save the sorting mode as alphabetical or by size when relaunching the app. A few bug fixes too, I'll list that in the release notes when it's ready though.
Looking forward to hearing what other suggestions you have!

**Comment by strash** [comment]
Yeah looks good!

**Comment by alienator88** [comment]
Closing this, features added in v3.4.0.
Feel free to open new FR issues if you have other ideas.
