### ISSUE TITLE
[BUG] App requesting reminders access

### ISSUE THREAD

**Issue by MED1975** [alienator88/Pearcleaner#42]
When launching the app for the first time you are prompted to grant access to Reminders

The app should not need this access or prompt for it. 

Version 3.4.1
macOS 14.4.1 M1 iMac

I am able to reset this request using 

tccutil reset Reminders com.alienator88.Pearcleaner

And on subsequent launches the permission is requested again.

**Comment by alienator88** [comment]
I honestly have no idea why that would be coming up, as the entitlements and the code only requests access to Full Disk permissions and Accessibility/System Events permissions. In order to request access to Reminders, I'd need to be using this function here and there's no trace of that in my app: https://developer.apple.com/documentation/eventkit/ekeventstore/4162273-requestfullaccesstoreminders

<br>

Pearcleaner Entitlements:
```
<key>com.apple.security.automation.apple-events</key>
<true/>
<key>com.apple.security.files.user-selected.read-only</key>
<true/>
```
<br>

Full Disk permission request code:
https://github.com/alienator88/Pearcleaner/blob/71a3b030d92d54e7fea3a7cad8a63c671e409033/Pearcleaner/Logic/Utilities.swift#L88

Accessibility permission request code:
https://github.com/alienator88/Pearcleaner/blob/71a3b030d92d54e7fea3a7cad8a63c671e409033/Pearcleaner/Logic/Utilities.swift#L121

<br>

Has this always been an issue for you? I've had no other reports of this since the app was released in November '23.

**Comment by MED1975** [comment]
Hi

Thanks for your reply. This is the first time I have installed your app, and is on a brand new Sonoma install so it’s very odd indeed.

As an aside, I am also prompted on every start of your app to grant other permissions. See the 2nd screenshots that shows what is going on.

[Screenshot 2024-04-10 at 17.10.04.png]

[Screenshot 2024-04-10 at 17.10.32.png]

Sent from my iPhone

On 10 Apr 2024, at 16:39, Alin Lupascu ***@***.***> wrote:

﻿
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

I honestly have no idea why that would be coming up, as the entitlements and the code only requests access to Full Disk permissions and Accessibility/System Events permissions. In order to request access to Reminders, I'd need to be using this function here and there's no trace of that in my app: https://developer.apple.com/documentation/eventkit/ekeventstore/4162273-requestfullaccesstoreminders


Pearcleaner Entitlements:

<key>com.apple.security.automation.apple-events</key>
<true/>
<key>com.apple.security.files.user-selected.read-only</key>
<true/>



Full Disk permission request code:
https://github.com/alienator88/Pearcleaner/blob/71a3b030d92d54e7fea3a7cad8a63c671e409033/Pearcleaner/Logic/Utilities.swift#L88

Accessibility permission request code:
https://github.com/alienator88/Pearcleaner/blob/71a3b030d92d54e7fea3a7cad8a63c671e409033/Pearcleaner/Logic/Utilities.swift#L121


Has this always been an issue for you? I've had no other reports of this since the app was released in November '23.

**Comment by alienator88** [comment]
I'm not seeing any attached screenshots btw, just the screenshot text.

If you go to your macos `Settings > Privacy & Security`, do you see Pearcleaner in the list for Full Disk Access and Accessibility?
If no, try to drag the app in there and enable the toggle.

Side note, is your profile on your mac a standard user or admin user?

**Comment by alienator88** [comment]
Is this still an issue?

**Comment by MED1975** [comment]
It was but I have removed it from my Mac now.
Sent from my iPhone

On 18 Apr 2024, at 18:27, Alin Lupascu ***@***.***> wrote:

﻿
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Is this still an issue?

**Comment by olshevski** [comment]
@alienator88 The app stills asks for the reminder permission:

<img width="1440" alt="Screenshot 2024-10-19 at 13 43 49" src="https://github.com/user-attachments/assets/5301a6a9-e293-422d-8e18-5a975fa5a491">

I was not asked for Full Disk Access and Accessibility and had to go and enable them manually. Not sure if I should have been asked for them, just followed your comment from this issue.

Pearcleaner 3.9.1
MacOS Sonoma 14.6.1

**Comment by alienator88** [comment]
I might know what's causing this now.
Can you let me know what app you clicked in the sidebar that triggered the permission alert?

**Comment by olshevski** [comment]
@alienator88 I was trying to delete App Cleaner & Uninstaller 😁

**Comment by alienator88** [comment]
HA!
So the reason it's coming up is because App Cleaner & Uninstaller is accessing reminders data in some way. 
I just installed it and this is the popup it showed me right when I launched it.
![image](https://github.com/user-attachments/assets/a8d1da4d-207e-4601-8d59-22239d57b5f5)

The reason Pearcleaner is asking for it now is because it found that accessed reminders data and it's trying to find all the relevant files for cleanup.
