### ISSUE TITLE
[BUG] Wrong size of .app in Finder and Pearcleaner

### ISSUE THREAD

**Issue by theramzay** [alienator88/Pearcleaner#46]
**Describe the bug**

Wrong size of `.app` in Finder and in `Pearcleaner`

**To Reproduce**
1. Go to `Apple App Store`
2. Find `Remote Desktop Scanner`
3. Download
4. Go to Applications folder in Fine and see size, then see size in `Pearcleaner`

**Expected behavior**

Same size of `.app` file in `Pearcleaner` and `Finder`

**Desktop (please complete the following information):**
 - OS: 14.3.1 (23D60)
 - Pearcleaner App Mode: Regular
 - Pearcleaner Version: 3.5.0

**Screenshots**

<img width="500" alt="image" src="https://github.com/alienator88/Pearcleaner/assets/5748239/172a787c-28a4-4cec-8a53-1132e0463f20">

**Comment by alienator88** [comment]
Hey, thanks for that!
I just looked at a few other apps on my end, and the size calculator seems to have trouble getting the exact size for the .app bundles. I'll work on this and see what I find.

**Comment by alienator88** [comment]
Out of curiosity I checked the other AppCleaner and it also gets the smaller size 😆 
![image](https://github.com/alienator88/Pearcleaner/assets/6263626/ebfd774f-2d5f-4c35-a2d3-cb048c8e9a93)

**Comment by alienator88** [comment]
So it turns out that there is no bug..there's 2 ways to get file sizes.

My app and the AppCleaner screenshot I just posted, use the `.totalFileAllocatedSizeKey` to get the size the app actually takes on disk. 
The AppCleaner screenshot you have, it looks like they decided to use the `.fileSizeKey` which does match Finder but is not accurate in terms of how much space it's actually taking on your drive. If you Get Info from Remote Desktop Scanner, you can see the size on disk is actually different than what Finder has, most likely. At least on my end it is.
![image](https://github.com/alienator88/Pearcleaner/assets/6263626/44a727f6-179c-4abe-a310-1118c2d3014b)


The `.fileSizeKey` gets the logical size of the file, but the `.totalFileAllocatedSizeKey` get the actual size, which could be different than the `.fileSizeKey` because modern operating systems use compression, deduplication and other features to lower the size a file actually takes on disk. Sometimes it can show bigger too, really depends on how many blocks it takes on the file system.

I personally think it makes more sense to get the actual size of disk space the app is using in this case.
But it's a preference, I could just add a setting in the app where the user can choose to show the logical app size or the size on disk size.

**Comment by alienator88** [comment]
Can also use this command to get the app size of the app from Terminal. This one should be different from Finder too:
`du -sk /PATH/TO/APP | cut -f1`

**Comment by theramzay** [comment]
Interesting! I think toggle will be nice solution. And/or maybe toggle to (full)view like in Finder info menu, like '9,787,635 bytes(4,6 on disk)'

So settings option like:

'Show size: [Finder-like size;Real Size; Finder-like(Real Size)]'

**Comment by alienator88** [comment]
Sounds good, I'll add that to the roadmap. I'm currently trying to get something else working and I haven't been able to get it working how I want all day. Once I finish that, I'll look at adding the setting.

**Comment by alienator88** [comment]
This has been added in v3.5.1
