### ISSUE TITLE
[BUG] Wrong name for app.

### ISSUE THREAD

**Issue by theramzay** [alienator88/Pearcleaner#47]
**Describe the bug**

Pearcleaner have wrong name for app.

**To Reproduce**
1. Download from [Notes Trainer](https://apps.apple.com/pl/app/notes-sight-reading-trainer/id874386416) App Store
2. Find app name in Apple Finder in Application folder
3. Look to name in Pearcleaner

Bonus:
Pearcleaner don’t see `Containers` too. Looks, like this is the bug for iOS apps only.

**Expected behavior**

Same name for app in Finder and in Pearcleaner.

**Desktop (please complete the following information):**
 - OS: 14.3.1 (23D60)
 - Pearcleaner App Mode: Regular
 - Pearcleaner Version: 3.5.1

**Screenshots**

<img width="500" alt="image" src="https://github.com/alienator88/Pearcleaner/assets/5748239/0ba5a6d7-0606-4e79-b21c-9c55d8fd3864">

**Comment by alienator88** [comment]
Looks like it's happening because the wrapped iOS app name shows as that inside the bundle and that's where I pulled the name from in iOS apps.
![image](https://github.com/alienator88/Pearcleaner/assets/6263626/ffbaf364-f9a0-4f25-977f-46bde7ba61dc)

I'll work on it and add a fix for that soon.
Thanks.

**Comment by alienator88** [comment]
Fixed in v3.5.2
Thanks!

**Comment by alienator88** [comment]
Just a quick FYI, I'll be pushing another update soon, maybe tomorrow or something where it will show the localized name of the file in the list to say Notes Trainer instead of the UUID of the folder, which is the actual name of the folder.
This is why Finder shows Notes Trainer and not the UUID, it uses the localized name.
![image](https://github.com/alienator88/Pearcleaner/assets/6263626/7e966544-fa80-4394-b55c-e79a1b13c199)

But the functionality of actually finding the files, should be good now on the current release.

**Comment by theramzay** [comment]
> Just a quick FYI, I'll be pushing another update soon, maybe tomorrow or something where it will show the localized name of the file in the list to say Notes Trainer instead of the UUID of the folder, which is the actual name of the folder. This is why Finder shows Notes Trainer and not the UUID, it uses the localized name. ![image](https://private-user-images.githubusercontent.com/6263626/324997804-7e966544-fa80-4394-b55c-e79a1b13c199.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzI0MzEsIm5iZiI6MTcxMzkzMjEzMSwicGF0aCI6Ii82MjYzNjI2LzMyNDk5NzgwNC03ZTk2NjU0NC1mYTgwLTQzOTQtYjU1Yy1lNzlhMWIxM2MxOTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjRUMDQxNTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjQyMTc3MjJjMWI3M2IxYTlhNWMwZWQyMjVmNGM3ZmI3NDM5ZGIzZGIxOThmMDViNGMxZTE5Y2JmMzY2MmU2ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Flsl7u4rwl_hqdzARmhAxnbKSvbABM0rHn0jay1d6wM)
> 
> But the functionality of actually finding the files, should be good now on the current release.

Great! Because I’m actually was thinking to make a Feature Request about this  )))
