### ISSUE TITLE
The name alienator88 should be removed from the Pearcleaner app files

### ISSUE THREAD

**Issue by 3onion** [alienator88/Pearcleaner#55]
**Describe the app**

When we uninstall the Pearcleaner application we see that it removes a series of files with the name "alienator88". I think that the mention of the name "alienator88" should be removed because some people who install it think that the app is from a hacker or that it is a malicious app. I say this because I've been asked if the app was trustworthy precisely because of that name. In my opinion, a solution should be found so as not to take away credit for the app and at the same time convey an image of trust in the app.

For example, you could use your name instead.

**App Details**
1. Name: Pearcleaner
2. Version:3.6.1
3. Source (AppStore Download, Website Download): Website
4. Type (Regular, Web, iOS): Regular

**Comment by alienator88** [comment]
Are you referring to my app's bundle ID, `com.alienator88.Pearcleaner`?

**Comment by 3onion** [comment]
> Are you referring to my app's bundle ID, `com.alienator88.Pearcleaner`?

Yes.

**Comment by alienator88** [comment]
I mean, that's my username here on GitHub. And the code is free to look at if anyone is worried about things like that. 

Not sure what the expectation is for me to use for my bundle id since I don't have a company name. Apple guidelines recommend using the bundle id when placing folders in the file system for an app to be easily distinguished.
