### ISSUE TITLE
[FR] App size in app list (+sort option)

### ISSUE THREAD

**Issue by woj-tek** [alienator88/Pearcleaner#62]
**Is your feature request related to a problem? Please describe.**

When I cleanup my machine I often like to remove "big apps" that I may not be using. Having appsize (+option to sort apps by size) would help with that

**Describe the solution you'd like**

Display app-size in the list next to a version (or instead?) with option to sort by it would be great.

**Comment by alienator88** [comment]
I have built this in now, but I'm playing around with a few things.
The issue I'm having is launching the app and generating the app list now takes a couple seconds longer than it used to because it has to run through each app and calculate the size. For some reason swift is kind of slow at that portion since it has to recursively go into the app bundle and get the size of all its files and sum them up.

I will try to find a way to calculate the sizes faster as first step.
But if I can't, I might add this under a setting which is off by default. Users who don't care to wait the extra couple seconds to launch the app, can enable this and show the sizes next to the app names.

This is what it looks like, hovering over an app shows the app version still:

![image](https://github.com/alienator88/Pearcleaner/assets/6263626/41defd3b-f39f-4c3d-aeb3-36b09b5e2eab)

**Comment by alienator88** [comment]
The sorting is already there, just no icon for it. Clicking the User or System headers flips to alphabetical or size sorting.

So lazy loading was one of the options I was playing with(my top choice currently), only thing I'm stuck on is say you have the sorting set to size on app load. If each item doesn't have sizes yet, how would the sorting behave? Default to alphabetical? But then once the sizes are fully loaded, the items would all move around to get in the right size sorting order. It seems jarring to the end-user experience. 

Another idea(2nd choice) I had was maybe cache the app list data like app name, icon, version and size via core data. These shouldn't change very often at all. Then on launch, load everything from the cache and process any new apps that might not be already in there and add those to the cache as well. Also refresh these cached apps if it's been longer than 7 days to keep details updated.

I'm not sure yet what direction to go with, but I do know I don't think I want that loading delay on app launch. So will need to figure something out 😄

**Comment by alienator88** [comment]
Give this a try and let me know what you think of the delay, maybe I'm overthinking it. For me, I have about 50 apps installed and it takes me 2-3 seconds to fully load in.
[Pearcleaner.zip](https://github.com/user-attachments/files/15791313/Pearcleaner.zip)

**Comment by alienator88** [comment]
Do you see any performance increase on this version? I changed the thread it runs on from .background to .userInitiated which should increase the speed and also fixed some UI choppiness when loading the apps.

[Pearcleaner.zip](https://github.com/user-attachments/files/15793172/Pearcleaner.zip)

**Comment by alienator88** [comment]
Scratch that last update, I think I got the lazy loading working really good now. It's pretty much instant in my testing. 
Let me know if this works!
As a side note, you can switch the sort order by clicking the headers and I also added a menu option in the search bar menu button.
[Pearcleaner.zip](https://github.com/user-attachments/files/15793871/Pearcleaner.zip)

**Comment by alienator88** [comment]
Pushed v3.7.0 out with this feature. 
Thanks for the input!

**Comment by alienator88** [comment]
Hi, so this is by design actually. When you click on an app in the sidebar, that's when Pearcleaner performs the actual file search and computes all the values. I didn't want to show the size of the app and all related files in the sidebar for a couple reasons:

1. It would take insanely long to search for every app and all of its files on load. I've actually done something like this with the app in the past where it loaded everything on launch and just did not like how long it took. For example in my case I use Brave Browser and the amount of files that app has, takes me like 3 or 4 seconds to load all of them. That's just 1 app. Imagine all of the apps at once.
2. Since these app cleaner type apps are never 100% exact on the files they find since they search based on the app name and bundle id, sometimes it finds unrelated files since some apps have similar names. Not very likely usually, but it can. So showing the app size + found files size in the sidebar could actually be incorrect if it finds unrelated files.

Since the sidebar holds the list of apps themselves, I thought it made sense to show the app's own size instead. The detail view on the right side is where all the found files and their sizes are shown. To me, these sizes seemed unrelated compared to the sidebar's function, which is just to show the app list and that's it. I hope this makes sense!

**Comment by alienator88** [comment]
In what way do you mean? 
The user is presented the list of files/folders the app "thinks" are related to the individual app. The user can either remove all or uncheck what might not be related.

**Comment by alienator88** [comment]
I mean, this is possible with any of these app cleaner apps.
I could add a popout warning button on the page, the same way I have on the Leftover files page. 
Something like how AppCleaner has as well:
![image](https://github.com/alienator88/Pearcleaner/assets/6263626/5362605f-74a5-4b1e-80a7-30d92dae8eb8)

**Comment by alienator88** [comment]
Sweet, I'll add that to the next update :)

**Comment by alienator88** [comment]
How is this? Right next to the delete button:
![image](https://github.com/alienator88/Pearcleaner/assets/6263626/fc07817e-f9d4-48a7-a722-42916bfbafec)
