### ISSUE TITLE
[APP] Emacs and AppCleaner (hope this one makes you smile)

### ISSUE THREAD

**Issue by hermannsorgel** [alienator88/Pearcleaner#70]
Emacs from [emacsformacosx](https://emacsformacosx.com)
Pearcleaner is going to delete the AppCleaner folders with Emacs (see screenshot).

**App Details**
1. Name: Emacs
2. Version: 29.3
3. Source: https://emacsformacosx.com
4. Type: Regular

**Desktop (please complete the following information):**
 - OS: macOS 14.5
 - Pearcleaner App Mode:  Regular
 - Pearcleaner Version:  3.7.3

**Screenshots**
<img width="901" alt="SCR-20240618-pgub-3" src="https://github.com/alienator88/Pearcleaner/assets/25165356/35fe8a9b-5401-4b55-8263-15913ae456bd">

**Comment by alienator88** [comment]
Ahhh haha, man gotta love apps with either very short names or too similar to other apps. 
That's why I added the condition builder in the last update. See that little hammer next to the uninstall button?
You can add either keywords or a full finder path to the Exclude fields, separated by commas. After you save the condition and run the search again, it should ignore those files.

As a test, I just added `freemacsoft` in the exclude keywords field and searched again and all those AppCleaner files are gone now:
![image](https://github.com/alienator88/Pearcleaner/assets/6263626/23475e97-b60a-4382-a956-b852e8060112)
![image](https://github.com/alienator88/Pearcleaner/assets/6263626/a12bfee1-d703-4818-ac23-e0924ac8b83f)

Let me know if this helps!

**Comment by alienator88** [comment]
FYI, condition builder has been moved to Tools menu in latest version. Can trigger it with CMD+B as well.
