### ISSUE TITLE
[FR] Storage map

### ISSUE THREAD

**Issue by Romachamp** [alienator88/Pearcleaner#79]
**Feature request**

I would like to see _storage map in PearCleaner, similar to the one in Disk Drill or Daisy Disk_. PearCleaner finds leftover files, which is great, but with the full map of my storage built in to the app, I would able to find more leftover files as well as see other big files on my disk. 

Thank you, in advance!

**Comment by alienator88** [comment]
That's a cool idea.
Just to clarify, would you want the storage map to show the files found in Leftover Files view, or should this be global and search the whole disk instead?

**Comment by Romachamp** [comment]
Search the whole disk map would be nice, and there could be marked leftover files as those, that I can safely delete, for example.

**Comment by alienator88** [comment]
Slight update, working on a little test app to see how the maps would look/work if I was able to add it in Pearcleaner.
I have 3 different views at the moment testing with some dummy files: bar chart, heat map and tree map. I think tree map is the usual one those disk tools use to allow you to drill down.

### Bar Chart
![Screenshot 2024-07-23 at 10 31 42 AM](https://github.com/user-attachments/assets/a605e944-f738-4860-bb76-e81c1c109da0)

### Heat Map
![Screenshot 2024-07-23 at 10 32 21 AM](https://github.com/user-attachments/assets/eb4ec903-cae6-4697-953c-977b3521eeb7)

### Tree Map
![Screenshot 2024-07-23 at 10 32 29 AM](https://github.com/user-attachments/assets/1dacbc86-e0e2-44a4-9a14-d7732fe8102a)


I'm hoping to be able to get the Tree Map and/or bar chart added to Pearcleaner. But it will take a bit of work, so won't be very soon.

**Comment by Romachamp** [comment]
Thanks for your work, so far, the best map is, in my opinion, the tree one. It reminds me Disk Drill or Daisy Disk and seems well implemented. No matter when this will be, I’m really excited about this feature, keep going, hoping to see it.

**Comment by alienator88** [comment]
That's what I'm leaning towards as well. It's pretty intuitive being able to click into each folder rectangle.
There's a couple UI/layout bugs here and there currently, but the main logic of it works good. 
The hardest part will be integrating this map into the existing app 😂

**Comment by alienator88** [comment]
Was able to get the layout on the tree map to look nicer by sorting the items from large to small.
Now they cascade from top left (big) to bottom right (small) like all those other disk mapping apps. 
Added some color and a tooltip with the name/size on hover of each box. 
Still unsure about the color, I was wanting to do blue for directories so you know you can click into them and then gray for files since you can't click into those any deeper. An alternative could be to do random colors and on click of directory, drill down more and on click of a file, open Finder where that file is.
What's your preference?

### Colored boxes
![image](https://github.com/user-attachments/assets/cf21fa76-870c-45b4-8fcf-66eda753c778)

### Blue/Gray boxes
![image](https://github.com/user-attachments/assets/aec40622-4d87-450a-8a7a-d901b10183b2)

All UI/layout bugs are fixed now though, so once I get back from vacation next week, I'll work on implementing this into Pearcleaner. Thanks again for the idea, I think this will help to set it apart from some of the other app cleaner apps out there.

**Comment by Romachamp** [comment]
Hello! The map looks better, I like it.

You could leave directories colorful, and for those you can’t go any deeper make them gray. 

On click on files, when you can go deeper, you could make going deeper like in Disk Drill. 

When you hover it sometimes shows the size, but in some cleaner apps it usually shows it without hovering by default.  So, maybe, you could remove gray color for tooltips, make them white/black(depends on the system theme of user) and make them be displayed for each folder/file without hovering. 

Opening in Finer and other buttons like this(delete, some other info, etc) could be shown at the top or somewhere as the separate panel, so the map will be more minimalistic.

**Comment by alienator88** [comment]
Hey, so after looking into this for a bit, it seems to be a pretty big undertaking trying to integrate it into Pearcleaner in a good/clean way.
If I were to add something like this, I might need to spin it off into its own separate app specifically for finding files on disk.
I'm going to close this request out for now and might pick it up in the future when I have more time.
