### ISSUE TITLE
[BUG] - Sequoia Finder Extension

### ISSUE THREAD

**Issue by KinanLak** [alienator88/Pearcleaner#84]
**Describe the bug:** <br>
When trying to enable the Finder Extension, Pearcleaner doesn't appear in the list of available Finder Extensions (see screenshot).

**Steps to reproduce:**
1. Go to Pearcleaner settings.
2. Click on the directory icon in the Finder Extension section.
3. A Settings window opens, but Pearcleaner is not listed :(

**Expected behavior** <br>
Pearcleaner should appear in this list.

**Info:**
- OS: macOS Sequoia 15 Beta 3
- Pearcleaner Version: 3.8.2

**Screenshots**

![CleanShot 2024-07-27 at 15 40 42](https://github.com/user-attachments/assets/ff8a7864-3335-4576-841b-13e1dc89cdbc)

**Additional context**
I'm using macOS Sequoia 15 Beta 3.

**Comment by alienator88** [comment]
Hey there, that's most likely because of the OS version you're on. There was another bug opened a little while back for an issue with the finder extension in Sequoia: https://github.com/alienator88/Pearcleaner/issues/68

Unfortunately until I update to Sequoia and build the Finder extension using the newer xcode version, it probably won't work right.

I'm only supporting public releases of macOS at the moment as Betas will have too many bugs: https://github.com/alienator88/Pearcleaner#requirements

**Comment by MuaiyadTSB** [comment]
@KinanLak @alienator88 

As a temporary workaround for those currently on Sequoia beta, you can use the following command to manually enable the extension in your terminal:

`pluginkit -e use -i com.alienator88.Pearcleaner`

Regarding the double window bug,  enabling the following commands in pearcleaner settings helps for now:

`One-Shot Mode ✅`
`Menubar icon ✅`

Also, @alienator88 Thank you for all that you do! Your work and efforts are appreciated!

Source [https://joelsenders.wordpress.com/2019/03/19/controlling-finder-extensions/](url)

**Comment by mh-saeed** [comment]
Unable to confirm deletion through Touch ID !
Is this linked to the above reported issue?

<img width="1512" alt="Screenshot 2024-09-19 at 1 53 41 AM" src="https://github.com/user-attachments/assets/62fab13b-86bd-495c-acf7-e145ed3e175d">

**Comment by alienator88** [comment]
I don't think this has anything to do with the Finder extension. The one in this issue is for when you right click an app insider Finder and lets you uninstall from the right click menu.
The popup you're seeing is presented by macOS, not Pearcleaner when Pearcleaner tells Finder to delete the files.
What OS version are you on?

**Comment by mh-saeed** [comment]
Mac OS sequoia Stable.

<img width="1512" alt="Screenshot 2024-09-19 at 2 37 47 AM" src="https://github.com/user-attachments/assets/aa9b4c53-895f-4d05-b11f-5253262a88da">

**Comment by alienator88** [comment]
I see..Pearcleaner hasn't been built/tested on Sequoia yet because I haven't had a chance to update my computer yet.
It could be related to that, I'm unsure. Did this work for you before on Sonoma?

**Comment by mh-saeed** [comment]
Yes, 
On Sonoma, I was not facing this issue!

**Comment by alienator88** [comment]
@mh-saeed I will put this into its own separate issue to track things better. I just updated my computer last night, so I'll play around with building a new version using the new xcode soon.

**Comment by alienator88** [comment]
@mh-saeed can you go to the new ticket I created for your issue and test the sequoia build I attached there please?

**Comment by alienator88** [comment]
@KinanLak @MuaiyadTSB This issue is now resolved and will be out in the next release. 
I'm fixing a couple more Sequoia bug and will try to get this out soon.
