### ISSUE TITLE
[FR] CLI support

### ISSUE THREAD

**Issue by martinvandiemen** [alienator88/Pearcleaner#95]
**Is your feature request related to a problem? Please describe.**

I would like to use Pearcleaner via the CLI to uninstall apps.

**Describe the solution you'd like**

Something like:
```pearcleaner --uninstall <BUNDLE_ID> or <APP_LOCATION>```

**Describe alternatives you've considered**

Currently manual.

**Additional context**

Let me know if you need more info.

**Comment by alienator88** [comment]
That's a good idea :)
I'll add it to the roadmap.

**Comment by alienator88** [comment]
That's doable..I'll add it to the list.

**Comment by Romachamp** [comment]
By the way, from CLI it could also uninstall homebrew casks. I mean, to use PearCleaner for both homebrew casks and apps from the internet/App Store. 

@alienator88 what do you think?

**Comment by martinvandiemen** [comment]
@alienator88 maybe --list would be better to show the relevant files? It would be nice if there would be an option to just uninstall the app (--uninstall) and the app with the relevant files (--uninstall-all).

**Comment by alienator88** [comment]
Okay, I see. So to recap:
1. `--list` should just output the possible files it finds for uninstall
2. `--uninstall` to remove only the application bundle
3. `--uninstall-all` to remove the application bundle and all related files

**Comment by alienator88** [comment]
Can someone test this debug build for me please? 
I added the basic CLI support discussed above. Enable from settings > general tab.
[Pearcleaner.zip](https://github.com/user-attachments/files/17051314/Pearcleaner.zip)

**Comment by alienator88** [comment]
Added CLI support in latest release. Closing this for now. 
Please reply back here if we need to reopen this for other CLI features, etc.

**Comment by johnmokos** [comment]
Is there a way to delete leftover files with cli?

**Comment by alienator88** [comment]
I could add it but it would be an all or nothing deletion. I'm not sure how safe that would be to do since a lot of found leftover files you might not want to delete. And having a long list of files might be difficult to manage from the CLI.

**Comment by johnmokos** [comment]
Yes you're right. But it still would be very valuable in my opinion. A lot of us try to keep our PCs as clean as possible, and already have excluded the folders we don't want to delete. So with this command at our disposal it would be just a "run" and then keep on doing our work. In any case we need to do some tinkering with our excluded files we can always come back to the GUI. 
* Thanks for the reply!

**Comment by alienator88** [comment]
Okay, yeah I see that use case. I can add a small warning in the CLI to make sure important folders/files have been excluded already. It won't take much to add a leftover files command now since the CLI framework is built already. I'll add it to the next release most likely.

**Comment by alienator88** [comment]
That's expected as it's not a valid command. `pearcleaner -h <path>` is nowhere in the help menu.
The CLI only supports providing a single application path. Not the applications folder where all apps are stored. See below:
```
[BETA] Pearcleaner CLI | Usage:

--list <path>, -l <path>             List application files available for uninstall at the specified path
--list-leftover, -lf                 List leftover files available for removal
--uninstall <path>, -u <path>        Uninstall only the application bundle at the specified path
--uninstall-all <path>, -ua <path>   Uninstall application bundle and ALL related files at the specified path
--remove-leftover, -rl               Remove ALL leftover files (To ignore files, add them to the exception list within Pearcleaner settings)
--help, -h                           Show this help message
```

**Comment by tsuliwaensis** [comment]
I mistyped. I meant to say `pearcleaner --list /Applications` but thank you for your explanation.

**Comment by alienator88** [comment]
No worries! 
Yeah I'm not sure how it would work if we were to list the related files to all apps in /Applications instead of one app at a time. It might get confusing 😄

**Comment by DavidRvrsR3** [comment]
Is your feature request related to a problem? Please describe.
I would love to use Pearcleaner to directly remove all files from an app with CLI while using an MDM solution
Therefore, I was happy to see there is CLI support.
Unfortunately if you use pearcleaner to clean up files, Finder is used to move files to Trash. 
(e.g. -ua -u -rl )
This then shows a prompt for admin credentials. 
This is unfortunate since I would like to minimize user interaction. 

Describe the solution you'd like
When i use Pearcleaner in the cli, with elevated rights, I would like to be able to remove the files without any user interaction.

Describe alternatives you've considered
using pearcleaner to list all installed files and create a custom script to remove the listed files. 

Additional context
Let me know if you have an need for more context

**Comment by alienator88** [comment]
I'll need to see how easy this would be to implement, I would probably have to create a whole new deletion mechanism for the CLI since the current one is built around Finder as you've seen. 
I'd probably need to do a check when running the commands to see if the uid is 0 matching root. If yes, then delete files using `mv` to move them to Trash instead of having Finder delete them and asking for password again.

**Comment by alienator88** [comment]
@DavidRvrsR3 version 4.3.0 which was just released, I moved away from AppleScript/Finder for deleting files.
It should work with using sudo at the cli now without prompting for a secondary set of admin credentials.
