### ISSUE TITLE
[FR] Add tilde prefixes and filter options for paths

### ISSUE THREAD

**Issue by khipp** [alienator88/Pearcleaner#96]
I'm using Pearcleaner to generate the paths for the `zap` stanzas used by `homebrew-cask` to clean up files after uninstalling an app:

```ruby
  zap trash: [
    "~/Library/Application Support/Signal",
    "~/Library/Preferences/org.whispersystems.signal-desktop.helper.plist",
    "~/Library/Preferences/org.whispersystems.signal-desktop.plist",
    "~/Library/Saved Application State/org.whispersystems.signal-desktop.savedState",
  ]
```

While this might not affect many users, it would be convenient if file paths for installed apps or leftover files could be copied with a tilde (`~`) prefix instead of the full path to the user's home directory. Additionally, a filter option to ignore temporary files and folders located in `/private/var` could be worth considering. This could be added as a simple toggle in the folder settings or above the file list.

**Comment by khipp** [comment]
I'm sorry; I wasn't aware of the export function.

I gave it a try and have the following thoughts:

- I'm unsure about the original use case, but would it make sense to export the results with one path per line without any additional formatting?
- It might be helpful to add a hotkey that simply copies the list to the clipboard instead of saving the results to a file first (maybe it's possible to use the default `Command-C`).
- It seems that exporting only works in the uninstaller and exports all items by default. Could it be adjusted to export only the selected entries? This wouldn't change the default functionality, as everything is pre-selected, but it would also allow this feature to be used in the leftover file search.

**Comment by alienator88** [comment]
I think your thoughts are valid, the feature wasn't too thought out initially, just came in as a request in the past.
I can look at doing the above.

**Comment by alienator88** [comment]
I'll have this out in the next release. Something to note:
1. I changed the formatting so it's just one path per line, using tilde ~ instead of the whole /Users/user prefix
2. Added a secondary command to copy to clipboard
3. In my testing, this already exports only the selected items in the list in the Uninstall page as it takes these URLs as a parameter from: appState.selectedItems. I just tested selecting only a couple items and only those got exported.

Unfortunately for the leftover file page, I had to use a non-published variable for the selected items since it can have a huge amount of files and publishing all those caused some performance issues in the past. For now I can't easily add the leftover files to the export command.
